services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
      #image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
        #- ./icons:/app/public/icons
    restart: unless-stopped
    env_file:
      - .env

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1
      device: ":/srv/docker/homepage/config"

networks:
  default:
    external: true
    name: homepage
