---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

# my-docker:
#   host: 127.0.0.1
#   port: 2375

 my-local-docker:
   socket: /var/run/docker.sock
   swarm: true

 my-pihole-docker:
   host: raspberrypi.tyler-clark.com
   port: 2375

 my-plex-docker:
   host: thinkcentre01.tyler-clark.com
   port: 2375
   swarm: true
 
 my-nextcloud-docker:
   host: nextcloud.tyler-clark.com
   port: 2375
   swarm: true

 my-fileserver-docker:
   host: fileserver.tyler-clark.com
   port: 2375
   swarm: true
 
