---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

# my-docker:
#   host: 127.0.0.1
#   port: 2375

 my-local-docker:
   socket: /var/run/docker.sock
   swarm: true

 my-pihole-docker:
   host: pihole.localdomain.lan
   port: 2375
