---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Tools:

  #- Rstudio Server:
  #      href: http://rstudio.tyler-clark.com
  #      description: Rstudio Server in nspawn container
  #      icon: rstudioserver
  
  - Nextcloud:
      href: https://nextcloud.tyler-clark.com
      description: Nextcloud
      icon: nextcloud
      server: my-local-docker
      container: nextcloud-aio-nextcloud
      widget:
        type: nextcloud
        url: https://nextcloud.tyler-clark.com/
        key: {{HOMEPAGE_VAR_NC_TOKEN}}

  
  - Homepage:
      href: https://homepage.tyler-clark.com
      description: Homepage Dashboard
      icon: homepage
      server: my-local-docker
      container: homepage
  
  - Traefik:
      href: https://traefik.tyler-clark.com/dashboard/
      description: Traefik 
      icon: traefik
      server: my-local-docker
      container: traefik
      widget: 
        type: traefik
        url: http://traefik:8080
        username: {{HOMEPAGE_TRAEFIK_USER}}
        password: {{HOMEPAGE_TRAEFIK_PASS}}

  
  - Calibre:
        href: https://calibre.tyler-clark.com
        description: Calibre eBook library management
        server: my-local-docker
        container: calibre
        icon: calibre
  
  - Mealie:
      href: https://mealie.tyler-clark.com
      description: Database of recipes
      server: my-local-docker
      container: mealie
      icon: mealie
      widget:
        type: mealie
        url: https://mealie.tyler-clark.com
        key: {{HOMEPAGE_VAR_MEALIE_KEY}}
        version: 2
  - Watchtower:
      description: Watchtower
      server: my-local-docker
      container: watchtower
      icon: watchtower
      widget:
        type: watchtower
        fields: ["containers_scanned", "containers_updated", "containers_failed"]
        url: https://watchtower.tyler-clark.com
        key: mytoken




- Multimedia:
    - Plex Media Server:
        href: http://plex.tyler-clark.com
        description: Plex Media Server
        server: my-plex-docker
        container: plex
        icon: plex
        widget:
          type: plex
          url: http://thinkcentre01.tyler-clark.com:32400
          key: {{HOMEPAGE_VAR_PLEX_KEY}}
  
    - Tautulli:
        #href: https://tautulli.tyler-clark.com
        href: http://thinkcentre01.tyler-clark.com:8181
        description: Plex stats
        server: my-plex-docker
        container: tautulli
        icon: tautulli
        widget:
          type: tautulli
          #url: https://tautulli.tyler-clark.com
          url: http://thinkcentre01.tyler-clark.com:8181
          key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false

    - Pasta:
        #href: https://pasta.tyler-clark.com
        href: http://thinkcentre01.tyler-clark.com:8087
        description: Pasta
        server: my-plex-docker
        container: pasta
        icon: /icons/pasta.png


    - Calibre Web:
        href: https://calibre-web.tyler-clark.com
        description: Calibre-web library browser
        server: my-local-docker
        container: calibre-web
        icon: calibre-web
        widget:
          type: calibreweb
          url: https://calibre-web.tyler-clark.com
          username: {{HOMEPAGE_VAR_CALIBRE-WEB_USER}}
          password: {{HOMEPAGE_VAR_CALIBRE-WEB_PASS}}
    - Radarr:
        href: http://radarr.tyler-clark.com
        description: Radarr
        server: my-local-docker
        container: radarr
        icon: radarr
    - Sonarr:
        href: http://sonarr.tyler-clark.com
        description: Sonarr
        server: my-local-docker
        container: sonarr
        icon: sonarr


- Network:
  - EdgeRouter:
      icon: edgeos
      href: https://192.168.0.1
      description: Ubiquiti EdgeRouter Login

  - Pihole:
      icon: pi-hole
      href: http://pihole.tyler-clark.com/admin
      description: Pihole ad blocker
      server: my-pihole-docker
      container: pihole
      widget:
        type: pihole
        url: http://raspberrypi.tyler-clark.com
        version: 6
        fields: ["queries", "blocked", "blocked_percent", "gravity"]
        key: {{HOMEPAGE_VAR_PIHOLE_TOKEN}}


  - UniFi Controller:
      href: https://unifi.tyler-clark.com:8443
      description: UniFi Controller software
      server: my-unifi-docker
      container: unifi-network-application
      icon: unifi-controller
      widget:
        type: unifi
        url: https://unifi.tyler-clark.com:8443
        key: {{HOMEPAGE_VAR_UNIFI_KEY}}
          #username: {{HOMEPAGE_VAR_UNIFI_USER}}
          #password: {{HOMEPAGE_VAR_UNIFI_PASS}}
  
  - Transmission:
      icon: transmission
      href: https://transmission.tyler-clark.com
      description: Transmission BitTorrent client
      server: my-local-docker
      container: transmission
      widget: 
        type: transmission
        url: https://transmission.tyler-clark.com
        fields: ["leech", "download", "seed", "upload"]  

