---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Tools:

  #- Rstudio Server:
  #      href: http://rstudio.localdomain.lan
  #      description: Rstudio Server in nspawn container
  #      icon: rstudioserver
  
  - Nextcloud:
      href: http://nextcloud.tyler-clark.com
      description: Nextcloud
      icon: nextcloud
      server: my-nextcloud-docker
      container: nextcloud_app
      widget:
        type: nextcloud
        url: http://nextcloud.localdomain.lan
        key: {{HOMEPAGE_VAR_NC_TOKEN}}

        #- Nginx Proxy Manager:
        #href: http://fileserver.localdomain.lan:81
        #description: Nginx Proxy Manager admin page
        #icon: nginx-proxy-manager
        #server: my-local-docker
        #container: nginx-proxy-manager

  - Nginx:
      description: Nginx 
      icon: nginx
      server: my-local-docker
      container: nginx
  
  - Calibre:
        href: http://calibre.localdomain.lan
        description: Calibre eBook library management
        server: my-local-docker
        container: calibre
        icon: calibre
  
  - Portainer:
        href: http://portainer.localdomain.lan
        description: Portainer CE
        server: my-local-docker
        container: portainer
        icon: portainer
  - Mealie:
      href: http://mealie.localdomain.lan
      description: Database of recipes
      server: my-local-docker
      container: mealie_app
      icon: mealie
      widget:
        type: mealie
        url: http://mealie.localdomain.lan
        key: {{HOMEPAGE_VAR_MEALIE_KEY}}
        version: 2




- Multimedia:
    - Plex Media Server:
        href: http://plex.localdomain.lan:32400
        description: Plex Media Server
        server: my-plex-docker
        container: plex
        icon: plex
        widget:
          type: plex
          url: http://plex.localdomain.lan:32400
          key: {{HOMEPAGE_VAR_PLEX_KEY}}
  
    - Tautulli:
        href: http://tautulli.localdomain.lan
        description: Plex stats
        server: my-local-docker
        container: tautulli_app
        icon: tautulli
        widget:
          type: tautulli
          url: http://tautulli.localdomain.lan
          key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false

    - Pasta:
        href: http://pasta.localdomain.lan
        description: Pasta
        server: my-local-docker
        container: pasta_app
        icon: /icons/pasta.png

    - Jellyfin:
        href: http://plex.localdomain.lan:8096
        description: Jellfin Media Server
        server: my-plex-docker
        container: jellyfin_app
        icon: jellyfin
        widget:
          type: jellyfin
          url: http://plex.localdomain.lan:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true

    - Calibre Web:
        href: http://calibre-web.localdomain.lan
        description: Calibre-web library browser
        server: my-local-docker
        container: calibre-web
        icon: calibre-web
        widget:
          type: calibreweb
          url: http://calibre-web.localdomain.lan
          username: {{HOMEPAGE_VAR_CALIBRE-WEB_USER}}
          password: {{HOMEPAGE_VAR_CALIBRE-WEB_PASS}}
    - Radarr:
        href: http://radarr.localdomain.lan
        description: Radarr
        server: my-local-docker
        container: radarr
        icon: radarr
    - Sonarr:
        href: http://sonarr.localdomain.lan
        description: Sonarr
        server: my-fileserver-docker
        container: sonarr_app
        icon: sonarr
    - Tdarr:
        href: http://tdarr.localdomain.lan
        description: Tdarr transcode utility
        server: my-local-docker
        container: tdarr
        icon: tdarr
        widget:
          type: tdarr
          url: http://tdarr.localdomain.lan


- Network:
  - EdgeRouter:
      icon: edgeos
      href: https://192.168.0.1
      description: Ubiquiti EdgeRouter Login

  - Pihole:
      icon: pi-hole
      href: http://pihole.localdomain.lan/admin
      description: Pihole ad blocker
      server: my-pihole-docker
      container: pihole
      widget:
        type: pihole
        url: http://pihole.localdomain.lan
        version: 5
        fields: ["queries", "blocked", "blocked_percent", "gravity"]
        key: {{HOMEPAGE_VAR_PIHOLE_TOKEN}}


  - UniFi Controller:
      href: https://unifi.localdomain.lan:8443
      description: UniFi Controller software
      server: my-unifi-docker
      container: unifi-network-application
      icon: unifi-controller
      widget:
        type: unifi
        url: https://unifi.localdomain.lan:8443
        username: {{HOMEPAGE_VAR_UNIFI_USER}}
        password: {{HOMEPAGE_VAR_UNIFI_PASS}}
  
  - Transmission:
      icon: transmission
      href: http://transmission.localdomain.lan
      description: Transmission BitTorrent client
      server: my-fileserver-docker
      container: transmission_app
      widget: 
        type: transmission
        url: http://transmission.localdomain.lan
        fields: ["leech", "download", "seed", "upload"]  

